### ISSUE TITLE
Threading reference collision

### ISSUE THREAD

**Issue by cyphactor** [codebreakdown/togls#35]
It seems like there is some sort of reference collision from the threading. I ran into it my test app with the following logs.

```
DREW: HooptyTogls::RuleRepositoryDrivers::HooptyJsonOverrideDriver::ToggleCache - priming: ["backend", "qa"]
DREW: fetching JSON for rules
DREW: HooptyTogls::ToggleRepositoryDrivers::HooptyJsonOverrideDriver::ToggleCache - priming: ["backend", "qa"]
DREW: fetching JSON for toggles
127.0.0.1 - - [16/Mar/2016:02:33:10 -0700] "GET  HTTP/1.1" 200 - 0.0044
DREW: HooptyTogls::RuleRepositoryDrivers::HooptyJsonOverrideDriver::ToggleCache - background_refresh: sleeping 15
2016-03-16 02:33:11 -0700: Rack app error: #<NoMethodError: undefined method `[]' for nil:NilClass>
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/togls-2.2.0/lib/togls/rule_repository.rb:44:in `reconstitute_rule'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/togls-2.2.0/lib/togls/rule_repository.rb:40:in `get'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/togls-2.2.0/lib/togls/toggle_repository.rb:40:in `reconstitute_toggle'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/togls-2.2.0/lib/togls/toggle_repository.rb:34:in `get'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/togls-2.2.0/lib/togls/feature_toggle_registry.rb:46:in `get'
/Users/adeponte/code/acorns/acorns_togls/lib/acorns_togls/business_toggle_registry_manager.rb:35:in `feature'
/Users/adeponte/code/garbage/bookshelf/apps/web/templates/home/index.html.erb:1:in `block in singleton class'
/Users/adeponte/code/garbage/bookshelf/apps/web/templates/home/index.html.erb:-6:in `instance_eval'
/Users/adeponte/code/garbage/bookshelf/apps/web/templates/home/index.html.erb:-6:in `singleton class'
/Users/adeponte/code/garbage/bookshelf/apps/web/templates/home/index.html.erb:-8:in `__tilt_70235837549420'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/template.rb:164:in `evaluate'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/tilt-2.0.2/lib/tilt/template.rb:99:in `render'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-view-0.6.1/lib/hanami/view/template.rb:41:in `render'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:117:in `rendered'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:131:in `layout'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:104:in `render'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-view-0.6.1/lib/hanami/view/rendering.rb:236:in `render'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/rendering_policy.rb:44:in `_render_action'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/rendering_policy.rb:37:in `_render'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/rendering_policy.rb:28:in `render'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/application.rb:109:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
(eval):15:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/routing/http_router.rb:135:in `raw_call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/router.rb:931:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/static.rb:31:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/container.rb:37:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/commonlogger.rb:31:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
DREW: HooptyTogls::ToggleRepositoryDrivers::HooptyJsonOverrideDriver::ToggleCache - background_refresh: sleeping 15
127.0.0.1 - - [16/Mar/2016:02:33:11 -0700] "GET /favicon.ico HTTP/1.1" 404 29 0.0011
127.0.0.1 - - [16/Mar/2016:02:33:12 -0700] "GET  HTTP/1.1" 200 - 0.0042
```

**Comment by cyphactor** [comment]
After briefly looking into this I think it is a side effect of the reference of the in memory hash being passed back as part of the in-memory drivers via the following:

```ruby
      def get(toggle_id)
        @toggles_lock.synchronize do
          @toggles[toggle_id]
        end
      end
```

I believe this could be resolved by simply adding a `dup` as follows:

```ruby
      def get(toggle_id)
        @toggles_lock.synchronize do
          @toggles[toggle_id].dup
        end
      end
```

**Comment by cyphactor** [comment]
I thought about this some more and neither `dup` nor `clone` will really solve this problem because they both do a **shallow copy**. What we would technically need is a **deep copy** which Ruby does not natively provide.

The best practice to my knowledge for this is really to use something like the following:

```ruby
copied_array = Marshal.load(Marshal.dump(complex_array))
```

Since our other drivers require marshaling anyways we may want to just have this driver use marshaling as well which will solve this problem as a side effect.

**Comment by cyphactor** [comment]
This issue has been resolved.
